server:
  port: 8085
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: service-test
