server:
  port: 8082

eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/
  instance:
    hostname: peer2
spring:
  application:
    name: eureka-server1